// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Z_ntpqrAPyS-N9h-slVD5zvONBq8OZE',
    appId: '1:988354498528:web:5a2b863cbe8fcde6406585',
    messagingSenderId: '988354498528',
    projectId: 'ppb-firebase-notificatio-bc97e',
    authDomain: 'ppb-firebase-notificatio-bc97e.firebaseapp.com',
    storageBucket: 'ppb-firebase-notificatio-bc97e.firebasestorage.app',
    measurementId: 'G-B12XVDG3C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrg1Q6xyksMnEKnvSiXvcR770A64-TBBw',
    appId: '1:988354498528:android:5ff2542f2f8b1d7b406585',
    messagingSenderId: '988354498528',
    projectId: 'ppb-firebase-notificatio-bc97e',
    storageBucket: 'ppb-firebase-notificatio-bc97e.firebasestorage.app',
  );
}
